print("Use prefixes to express numbers in bases that are not 10")
print("0b for binary (ex. 0b11001 is 11001 in binary)")
print("0o for octal")
print("0x for hexadecimal")
expression = int(eval(input("Expression: ")))
print(f"Base 2: {expression :b}")
print(f"Base 8: {expression :o}")
print(f"Base 10: {expression :d}")
print(f"Base 16: {expression :X}")